import './globals.css'
import type { Metadata } from 'next'
import { Inter, Pixelify_Sans } from 'next/font/google' // Importamos la fuente Pixelify Sans desde next/font
import Nav from '@/components/Nav'
import Providers from './Providers'
import Footer from '@/components/Footer'

// Cargar la fuente 'Inter'
const inter = Inter({ subsets: ['latin'] })
// Cargar la fuente 'Pixelify Sans'
const pixelifySans = Pixelify_Sans({ weight: ['700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pixel Arcade',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={`${inter.className} ${pixelifySans.className}`}>
        <Providers>
          <Nav />
          <div className='indexCoverBack mt-16'>
            {children}
          </div>
        </Providers>
        <Footer />
      </body>
    </html>
  )
}
